# Generated by Django 6.0.6 on 2026-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Champions League Final or Arsenal vs Chelsea', max_length=150)),
                ('sport_type', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Athletics', 'Athletics'), ('Rugby', 'Rugby'), ('Other', 'Other')], default='Football', max_length=50)),
                ('description', models.TextField(help_text='Add match predictions, tactical notes, or general details.')),
                ('event_date', models.DateTimeField(blank=True, help_text='The exact date and time of the match/event', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Check if this event has already finished')),
            ],
        ),
    ]
