# Generated by Django 6.0.6 on 2026-06-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportItems',
        ),
    ]
